<UnitGfx>:
        source: None
        image: gfximage
        animation: {}
        
        Image:
                id: gfximage
                source: root.source
                pos: root.pos
                size: (32, 32)


<BrickGfx>:
        source: 'img/caisse.jpg'


<HeroGfx>:
        source: 'img/mario/mariowalk.zip'
        walk: 'img/mario/mariowalk.zip'
        jump: 'img/mario/mariojump.zip'

<EnemiGfx>:
        source: 'img/mario/fierywalk.zip'


